### ISSUE TITLE
TLS 1.2

### ISSUE THREAD

**Issue by WaltMit** [CrestApps/RetsConnector#6]
Will this work with TLS 1.2? I have been using ezRETS for 10 years and the CRMLS just started requiring all RETS clients be TLS 1.2 compliant. I am really hoping this will work.

**Comment by WaltMit** [comment]
I'm hopeful this does use TLS 1.2 because I found this on stackoverflow:

.net core 3.1 used tls 1.2 is by default so nothing to do:
https://stackoverflow.com/questions/63451303/how-to-enable-tls-1-2-in-asp-net-core-3-1

**Comment by MikeAlhayek** [comment]
Sorry I just saw this. Are you good here or do you need help?

**Comment by WaltMit** [comment]
Hi,



Thank you very much. I am good now. I could not get your example console application to work but I found a sample project link in one of the closed issues on github for your project titled: "RetsConnector-master-zBestData-09-23-2019" posted by Graham Davis. I was able to edit that sample project, which uses your RetsConnector, and get it working with the CRMLS RETS feed that requires TLS 1.2.



So, thank you very much for creating RetsConnector in the first place. It was the best way I could find to integrate with RETS. All of the old LibRets documentation is gone since the CRT website is dead and LibRets does not appear to be being maintained.



Also, you may want to reach out to reso.org and ask them to include your RetsConnector client on their webpage for recommended RETS clients since it appears to be the only RETS client I know of that is TLS 1.2 compliant and works.



Thank you very much for creating RetsConnector and your reply,

Charlie Stephens


On March 6, 2021 at 8:35 AM, CrestApps <notifications@github.com> wrote:






Sorry I just saw this. Are you good here or do you need help?
