### ISSUE TITLE
QueryParameter

### ISSUE THREAD

**Issue by WaltMit** [CrestApps/RetsConnector#8]
The example has this:
     searchRequest.ParameterGroup.AddParameter(new QueryParameter("matrix_unique_id", "0+"));

So how would I get these as QueryParameters?:

WHERE   City IN ('CHIC', 'BUTV', 'DURH', 'COHA', 'RCHV', 'FORA') 
               AND ModificationTimestamp  >=  new_filter_time 

Sorry for all the issues I am having. If you help me get this working I will find a way to pay you for the help. I have 9 days to replace ezRETS with this. I am desperate and not nearly as good of a programmer as whoever created this.

**Comment by zBestData** [comment]
WaltMit,

I did some patch work to this project and will help you if I can.  I am located in Durham, NC on Eastern Standard Time.  I am at gdavis@zbestdata.com

Graham

**Comment by WaltMit** [comment]
Thanks Graham the example console application you posted here: 

https://github.com/CrestApps/RetsConnector/issues/3
https://github.com/CrestApps/RetsConnector/files/3643515/RetsConnector-master-zBestData-09-23-2019.zip

worked for me after updating the target framework to .NET Core 3.1 and changing RetsClient.cs to have  this           query.Add("Query", request.ParameterGroup.ToString());. So thank you very much!

To answer my own questions and close the issue I posted above this is how you query for all listings within 5 cities:

searchRequest.ParameterGroup.AddParameter(new QueryParameter("City", "CHIC,BUTV,DURH,COHA,RCHV,FORA"));

and this is how you can search for modified listings greater than a date/time:

searchRequest.ParameterGroup.AddParameter(new QueryParameter("ModificationTimestamp", new_filter_time + "+"));
